/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class cats extends javax.swing.JFrame {

    /**
     * Creates new form cats
     */Connection con;
    public cats() {
        initComponents();
        createConnection();
        autofillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cattable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        catCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(1279, 519));
        setPreferredSize(new java.awt.Dimension(1300, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("cats");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 0, 1280, 70);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        cattable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pet_name", "birth_date", "gender", "size", "color", "intake_date", "adoption_state"
            }
        ));
        jScrollPane1.setViewportView(cattable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("breed");

        catCombo.setMaximumRowCount(17);
        catCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abyssinaian Cat ", "American curl cat ", "Origi", "valverde", "Bengal", "Birman Cat ", "Burmese Cat ", "Chartreux Cat ", "Egyption Mau Cat ", "Devoon Rex Cat ", "Himalayan Cat ", "Japanese Bobtail Cat", "Maine Coon Cat ", "Manx", "Oriental Cat ", "Persian Cat", "Ragamuffin Cat", "Scottish Fold Cat " }));
        catCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(150, 150, 150)
                .addComponent(catCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(catCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1280, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catComboActionPerformed
         Object obj = evt.getSource();
        if(obj==catCombo)
        {
            fillTable();
        }
    }//GEN-LAST:event_catComboActionPerformed

     void createConnection() {
        String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(cats.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    void fillTable() {

        DefaultTableModel tablemodel = (DefaultTableModel) cattable.getModel();
        tablemodel.getDataVector().removeAllElements();

        try {
            int breedID =0;
            String adoption = null;
            Statement state = con.createStatement();
            ResultSet rst = state.executeQuery("SELECT brees_id FROM animalsshelter.breeds where  breed_name = '"+catCombo.getSelectedItem().toString()+"'");
            while (rst.next()) { breedID = rst.getInt("brees_id"); }
            state.close();
            rst.close();
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM animalsshelter.pets where specie_id = 2 and breed_id = "+breedID);
            while (rs.next()) {
                String rabitName = rs.getString("pet_name");
                String rabitbirth = rs.getString("birth_date");
                String rabitgendr = rs.getString("gender");
                String size = rs.getString("size");
                String color = rs.getString("color");
                String intakedate = rs.getString("intake_date");
                int adoptionstat = rs.getInt("adoption_state");
                
                if(adoptionstat==0)
                    adoption="Not Adopted";
                else 
                    adoption="Adopted";

                tablemodel.addRow(new Object[]{rabitName, rabitbirth, rabitgendr, size,color,intakedate,adoption});
            }

            stat.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(cats.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
     void autofillTable() {

        DefaultTableModel tablemodel = (DefaultTableModel) cattable.getModel();
        tablemodel.getDataVector().removeAllElements();

        try {
            String adoption =null;
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM animalsshelter.pets where specie_id = 2 ");
            while (rs.next()) {
                String rabitName = rs.getString("pet_name");
                String rabitbirth = rs.getString("birth_date");
                String rabitgendr = rs.getString("gender");
                String size = rs.getString("size");
                String color = rs.getString("color");
                String intakedate = rs.getString("intake_date");
                int adoptionstat = rs.getInt("adoption_state");
                
                if(adoptionstat==0)
                    adoption="Not Adopted";
                else 
                    adoption="Adopted";

                tablemodel.addRow(new Object[]{rabitName, rabitbirth, rabitgendr, size,color,intakedate,adoption});
            }

            stat.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(cats.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catCombo;
    private javax.swing.JTable cattable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
