/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;  
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class delete_client1 extends javax.swing.JFrame {

    int meddicalstate;
    Connection con;
    public delete_client1() {
        initComponents();
        createConnection();
        fillfirstNamecombo();
        fillLastNamecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameCombo = new javax.swing.JComboBox<>();
        lastNameCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        bdate = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        noAllergy = new javax.swing.JRadioButton();
        catAllergy = new javax.swing.JRadioButton();
        birdAllergy = new javax.swing.JRadioButton();
        dogAllergy = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/low-angle-photo-of-bird-flying-across-dark-clouds-2715005 (2).jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(669, 640));
        setPreferredSize(new java.awt.Dimension(669, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/go-back-icon.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(820, 550, 65, 50);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Delete client");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 70);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("last name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 70, 250, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("first name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 20, 270, 40);

        firstNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameComboActionPerformed(evt);
            }
        });
        jPanel2.add(firstNameCombo);
        firstNameCombo.setBounds(380, 40, 151, 22);

        lastNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameComboActionPerformed(evt);
            }
        });
        jPanel2.add(lastNameCombo);
        lastNameCombo.setBounds(380, 90, 151, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("phone number");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 173, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("adress");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 200, 77, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("medical state");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(480, 160, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 320, 90, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 380, 66, 40);

        phone.setEditable(false);
        phone.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(phone);
        phone.setBounds(280, 150, 151, 30);

        adress.setEditable(false);
        adress.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(adress);
        adress.setBounds(280, 210, 151, 30);

        bdate.setEditable(false);
        bdate.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(bdate);
        bdate.setBounds(280, 270, 151, 30);

        id.setEditable(false);
        id.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(id);
        id.setBounds(280, 330, 150, 30);

        email.setEditable(false);
        email.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(email);
        email.setBounds(280, 380, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("birth date");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 270, 117, 30);

        noAllergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(noAllergy);
        noAllergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        noAllergy.setForeground(new java.awt.Color(255, 255, 255));
        noAllergy.setText("no_allergy");
        jPanel2.add(noAllergy);
        noAllergy.setBounds(480, 210, 125, 39);

        catAllergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(catAllergy);
        catAllergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        catAllergy.setForeground(new java.awt.Color(255, 255, 255));
        catAllergy.setText("cat_allergy");
        jPanel2.add(catAllergy);
        catAllergy.setBounds(480, 250, 137, 39);

        birdAllergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(birdAllergy);
        birdAllergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        birdAllergy.setForeground(new java.awt.Color(255, 255, 255));
        birdAllergy.setText("birds_allergy");
        jPanel2.add(birdAllergy);
        birdAllergy.setBounds(480, 290, 153, 39);

        dogAllergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(dogAllergy);
        dogAllergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        dogAllergy.setForeground(new java.awt.Color(255, 255, 255));
        dogAllergy.setText("dog_allergy");
        jPanel2.add(dogAllergy);
        dogAllergy.setBounds(480, 330, 137, 39);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(255, 153, 0), null, null));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 460, 220, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 670, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameComboActionPerformed
                Object obj = evt.getSource();
        if(obj==firstNameCombo)
        {
                int clientID = 0;
                try {
                    String sql = "select membership_id from animalsshelter.clients_info where first_name = '" + (firstNameCombo.getSelectedItem().toString()) + "'";
                    Statement prep = con.createStatement();
                    ResultSet rst = prep.executeQuery(sql);//resultset contain 1 coloumn the first name
                    
                    while (rst.next())
                    {
                        clientID = rst.getInt(1);
                    }
                    prep.close();
                    rst.close();
                }
                catch (SQLException ex)
                {
                    Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                fillLastNamecombo();
                
            try {    
                String sqlqry = "select last_name from animalsshelter.clients_info where membership_id = "+clientID;
                PreparedStatement prepred = con.prepareStatement(sqlqry);
                ResultSet resultbred =  prepred.executeQuery();
                
                while (resultbred.next()){
                    lastNameCombo.setSelectedItem(resultbred.getString("last_name"));
                    
                }
                prepred.close();
                resultbred.close();
                
            } 
            catch (SQLException ex)
            {
                Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
            }
            //lastNCombo.removeAllItems();
            
        }

    }//GEN-LAST:event_firstNameComboActionPerformed

    private void lastNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameComboActionPerformed
             Object obj = evt.getSource();
        if(obj==lastNameCombo)
        {
        try {
            String sql = "select  birth_date , phone_number , adress , email , medical_state , clients_id from animalsshelter.clients_info where first_name = '"+(firstNameCombo.getSelectedItem().toString())+"' and last_name = '"+(lastNameCombo.getSelectedItem().toString())+"'";
            Statement prep = con.createStatement();
            ResultSet rst =  prep.executeQuery(sql);//resultset contain 5 coloumns found by the first name & last
            
            while(rst.next())
            {
                meddicalstate = rst.getInt("medical_state");
                phone.setText(rst.getString("phone_number"));
                bdate.setText(rst.getString("birth_date"));
                adress.setText(rst.getString("adress"));
                email.setText(rst.getString("email"));
                id.setText(rst.getString("clients_id"));
            }
            prep.close();
            rst.close();
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
            switch (meddicalstate) {
                case 1:
                    noAllergy.setSelected(true);
                    break;
                case 2:
                    dogAllergy.setSelected(true);
                    break;
                case 3:
                    catAllergy.setSelected(true);
                    break;
                case 4:
                    birdAllergy.setSelected(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error! No Meddical Statement Found.");
                    break;
            }
        }

    }//GEN-LAST:event_lastNameComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
         int client_id = 0;
        try {                                         
            
            String sqll = "select membership_id from animalsshelter.clients_info where first_name = '"+firstNameCombo.getSelectedItem().toString()+"' and last_name = '"+lastNameCombo.getSelectedItem().toString()+"'";
            PreparedStatement stmtt = con.prepareStatement(sqll);
            ResultSet result = stmtt.executeQuery();
            while (result.next())
            {
                client_id = result.getInt("membership_id");
            }
            stmtt.close();
            result.close();
            
            try {
                String sql ="delete from animalsshelter.clients_info where membership_id = "+client_id;
                PreparedStatement stt = con.prepareStatement(sql);
                stt.executeUpdate();
                stt.close();
                JOptionPane.showMessageDialog(null, "Client Deleted Successfully.");
                fillfirstNamecombo();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

     private void fillfirstNamecombo()
     {
        try {
            String sqll = "SELECT first_name FROM animalsshelter.clients_info";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                firstNameCombo.addItem(rst.getString("first_name"));
                
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
    
    private void fillLastNamecombo()
     {
        try {
            String sqll = "SELECT last_name FROM animalsshelter.clients_info where first_name = '"+(firstNameCombo.getSelectedItem().toString())+"'";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                lastNameCombo.addItem(rst.getString("last_name"));
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
    
    void createConnection()
    {
         String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(delete_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_client1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JTextField bdate;
    private javax.swing.JRadioButton birdAllergy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton catAllergy;
    private javax.swing.JRadioButton dogAllergy;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> firstNameCombo;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lastNameCombo;
    private javax.swing.JRadioButton noAllergy;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
