/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
        

/**
 *
 * @author BT
 */
public class delete_animal1 extends javax.swing.JFrame {
        
    Connection con;
    String genderrr;
    int adoptionStatement;
    /**
     * Creates new form delete_animal
     */
    public delete_animal1() {
        initComponents();
        createConnection();
        fillPetNamecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        color = new javax.swing.JTextField();
        intakeDate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NamesCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        birthdatePet = new javax.swing.JTextField();
        malebutton = new javax.swing.JRadioButton();
        femalebuton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        adoptionDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adoptedButton = new javax.swing.JRadioButton();
        notadoptedButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        sizeee = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(670, 640));
        setPreferredSize(new java.awt.Dimension(669, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        color.setEditable(false);
        color.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(color);
        color.setBounds(250, 360, 140, 30);

        intakeDate.setEditable(false);
        intakeDate.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(intakeDate);
        intakeDate.setBounds(250, 410, 140, 30);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Delete animal");
        jPanel1.add(jLabel10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 80);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pet name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 20, 230, 45);

        NamesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamesComboActionPerformed(evt);
            }
        });
        jPanel2.add(NamesCombo);
        NamesCombo.setBounds(370, 30, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("birth date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 100, 200, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("gender");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 160, 170, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("size");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 130, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("intake date");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 340, 210, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("color");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 280, 140, 29);

        birthdatePet.setEditable(false);
        birthdatePet.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(birthdatePet);
        birthdatePet.setBounds(250, 100, 140, 30);

        malebutton.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(malebutton);
        malebutton.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        malebutton.setForeground(new java.awt.Color(255, 255, 255));
        malebutton.setText("male");
        jPanel2.add(malebutton);
        malebutton.setBounds(250, 160, 73, 39);

        femalebuton.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(femalebuton);
        femalebuton.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        femalebuton.setForeground(new java.awt.Color(255, 255, 255));
        femalebuton.setText("female");
        jPanel2.add(femalebuton);
        femalebuton.setBounds(380, 160, 100, 39);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("adoption date");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 390, 180, 29);

        adoptionDate.setEditable(false);
        adoptionDate.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(adoptionDate);
        adoptionDate.setBounds(250, 390, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("adoption state");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 450, 200, 29);

        adoptedButton.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(adoptedButton);
        adoptedButton.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        adoptedButton.setForeground(new java.awt.Color(255, 255, 255));
        adoptedButton.setText("adoptted");
        jPanel2.add(adoptedButton);
        adoptedButton.setBounds(240, 430, 140, 39);

        notadoptedButton.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(notadoptedButton);
        notadoptedButton.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        notadoptedButton.setForeground(new java.awt.Color(255, 255, 255));
        notadoptedButton.setText("not adoptted");
        jPanel2.add(notadoptedButton);
        notadoptedButton.setBounds(390, 430, 170, 39);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(255, 153, 0), null, null));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 480, 200, 50);

        sizeee.setEditable(false);
        sizeee.setBackground(new java.awt.Color(204, 204, 204));
        sizeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeeeActionPerformed(evt);
            }
        });
        jPanel2.add(sizeee);
        sizeee.setBounds(250, 229, 140, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 670, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamesComboActionPerformed
        // TODO add your handling code here:
        Object obj = evt.getSource();
        if(obj==NamesCombo)
        {
            try {
                String sql = "select birth_date , gender , size , color , intake_date , adoption_state , adoption_date  from animalsshelter.pets where pet_name = '"+(NamesCombo.getSelectedItem().toString())+"'";
                Statement prep = con.createStatement();
                ResultSet rst =  prep.executeQuery(sql);//resultset contain 7 coloumns by the pet name
                
                while(rst.next())
                {//each textfield will have the value of th 10 coloumns we selected from pets table
                    birthdatePet.setText(rst.getString("birth_date"));
                    color.setText(rst.getString("color"));
                    intakeDate.setText(rst.getString("intake_date"));
                    adoptionDate.setText(rst.getString("adoption_date"));
                    genderrr = rst.getString("gender");
                    sizeee.setText(rst.getString("size"));
                    adoptionStatement = rst.getInt("adoption_state");
                }
                prep.close();
                rst.close();
            } catch (SQLException ex) {
                Logger.getLogger(delete_animal1.class.getName()).log(Level.SEVERE, null, ex);
            }
            // adoption stete previous value
        
            switch (adoptionStatement) {
                case 0:
                   notadoptedButton.setSelected(true);
                    break;
                case 1:
                   adoptedButton.setSelected(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error! No Adoption Statement Found.");
                    break;
            }
            // gender previous value
            
            switch (genderrr) {
                case "Male":
                   malebutton.setSelected(true);
                    break;
                case "Female":
                    malebutton.setSelected(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error! No Gender Found.");
                    break;
            }
        
        }

        
    }//GEN-LAST:event_NamesComboActionPerformed

    private void sizeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeeeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sizeeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int pet_id = 0;
        try {                                         
            
            String sqll = "select pet_id from animalsshelter.pets where pet_name = '"+NamesCombo.getSelectedItem().toString()+"'";
            PreparedStatement stmtt = con.prepareStatement(sqll);
            ResultSet result = stmtt.executeQuery();
            while (result.next())
            {
                pet_id = result.getInt("pet_id");
            }
            stmtt.close();
            result.close();
            
            try {
                String sql ="delete from animalsshelter.pets where pet_id = "+pet_id;
                PreparedStatement stt = con.prepareStatement(sql);
                stt.executeUpdate();
                stt.close();
                JOptionPane.showMessageDialog(null, "Animal Deleted Successfully.");
                fillPetNamecombo();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(delete_animal1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(delete_animal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed
         
    
    private void fillPetNamecombo()
     {
        try {
            String sqll = "SELECT * FROM animalsshelter.pets";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                String petsNames = rst.getString("pet_name");
                NamesCombo.addItem(petsNames);
                
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(delete_animal1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
    void createConnection()
    {
         String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(delete_animal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_animal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_animal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_animal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_animal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_animal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NamesCombo;
    private javax.swing.JRadioButton adoptedButton;
    private javax.swing.JTextField adoptionDate;
    private javax.swing.JTextField birthdatePet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField color;
    private javax.swing.JRadioButton femalebuton;
    private javax.swing.JTextField intakeDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton malebutton;
    private javax.swing.JRadioButton notadoptedButton;
    private javax.swing.JTextField sizeee;
    // End of variables declaration//GEN-END:variables
}
