/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
public class delete_empolyee1 extends javax.swing.JFrame {

    Connection con;
    public delete_empolyee1() {
        initComponents();
        createConnection();
        fillCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namesCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(670, 640));
        setPreferredSize(new java.awt.Dimension(669, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/go-back-icon.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(830, 550, 65, 41);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete empolyee");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 70);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 30, 150, 44);

        namesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesComboActionPerformed(evt);
            }
        });
        jPanel2.add(namesCombo);
        namesCombo.setBounds(350, 40, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 180, 120, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 240, 170, 29);

        email.setEditable(false);
        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setEnabled(false);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(370, 170, 170, 40);

        pass.setEditable(false);
        pass.setBackground(new java.awt.Color(204, 204, 204));
        pass.setEnabled(false);
        jPanel2.add(pass);
        pass.setBounds(370, 230, 170, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(255, 153, 0), null, null));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(210, 440, 220, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 670, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesComboActionPerformed
                
         Object obj = evt.getSource();
        if(obj==namesCombo)
        {
             try {
                 String query = "select employee_email , employee_password from animalsshelter.employees_info where employee_name = '"+namesCombo.getSelectedItem().toString()+"'";
                 Statement state = con.createStatement();
                 ResultSet rest = state.executeQuery(query);
                 while (rest.next())
                 {
                     email.setText(rest.getString("employee_email"));
                     pass.setText(rest.getString("employee_password"));
                 }
                 state.close();
                 rest.close();
             } catch (SQLException ex) {
                 Logger.getLogger(delete_empolyee1.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
   
    }//GEN-LAST:event_namesComboActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                int emp_id = 0;
        try {                                         
            
            String sqll = "select employee_id from animalsshelter.employees_info where employee_name = '"+namesCombo.getSelectedItem().toString()+"'";
            PreparedStatement stmtt = con.prepareStatement(sqll);
            ResultSet result = stmtt.executeQuery();
            while (result.next())
            {
                emp_id = result.getInt("employee_id");
            }
            stmtt.close();
            result.close();
            
            try {
                String sql ="delete from animalsshelter.employees_info where employee_id = "+emp_id;
                PreparedStatement stt = con.prepareStatement(sql);
                stt.executeUpdate();
                stt.close();
                JOptionPane.showMessageDialog(null, "Employee Deleted Successfully.");
                fillCombobox();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(delete_empolyee1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(delete_empolyee1.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

     void createConnection()
    {
         String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(delete_empolyee1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    private void fillCombobox()
    {
        try {
            String sqll = "SELECT * FROM animalsshelter.employees_info";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                String name = rst.getString("employee_name");
                namesCombo.addItem(name);
                
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(delete_empolyee1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_empolyee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_empolyee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_empolyee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_empolyee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_empolyee1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> namesCombo;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
