/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;

//import static project.add_animal.convertUtilToSql;
import static animalshleter.add_animal1.convertUtilToSql;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;  
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class edit_client1 extends javax.swing.JFrame {

    Connection con;
    int meddicalstate=0;
    int clientId = 0;  
    int allrgy=0;
    public edit_client1() {
        initComponents();
        createConnection();
        fillfirstNamecombo();
       fillLastNamecombo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        client_fN = new javax.swing.JTextField();
        client_ln = new javax.swing.JTextField();
        birthDate = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        client_email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        noallergy = new javax.swing.JRadioButton();
        catallergy = new javax.swing.JRadioButton();
        dogallergy = new javax.swing.JRadioButton();
        birdallergy = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNCombo = new javax.swing.JComboBox<>();
        lastNCombo = new javax.swing.JComboBox<>();

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/low-angle-photo-of-bird-flying-across-dark-clouds-2715005 (2).jpg"))); // NOI18N
        jLabel7.setText("Edit client");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(650, 640));
        setPreferredSize(new java.awt.Dimension(669, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edit client");
        jPanel1.add(jLabel8);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 80);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("first name");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 120, 190, 80);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("medical state");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(430, 130, 170, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("birth date");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 240, 190, 50);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("phone number");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 290, 190, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("adress");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 340, 160, 50);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("email");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 390, 65, 50);

        client_fN.setBackground(new java.awt.Color(247, 250, 247));
        jPanel2.add(client_fN);
        client_fN.setBounds(210, 140, 150, 40);

        client_ln.setBackground(new java.awt.Color(247, 250, 247));
        jPanel2.add(client_ln);
        client_ln.setBounds(210, 190, 150, 40);

        birthDate.setBackground(new java.awt.Color(247, 250, 247));
        birthDate.setToolTipText("yyyy/mm/dd");
        jPanel2.add(birthDate);
        birthDate.setBounds(210, 240, 150, 40);

        phone.setBackground(new java.awt.Color(247, 250, 247));
        jPanel2.add(phone);
        phone.setBounds(210, 300, 150, 40);

        address.setBackground(new java.awt.Color(247, 250, 247));
        jPanel2.add(address);
        address.setBounds(210, 350, 150, 40);

        client_email.setBackground(new java.awt.Color(247, 250, 247));
        jPanel2.add(client_email);
        client_email.setBounds(210, 400, 150, 40);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("last name");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 180, 170, 60);

        noallergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(noallergy);
        noallergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        noallergy.setForeground(new java.awt.Color(255, 255, 255));
        noallergy.setText("no_allergy");
        noallergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noallergyActionPerformed(evt);
            }
        });
        jPanel2.add(noallergy);
        noallergy.setBounds(430, 180, 150, 39);

        catallergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(catallergy);
        catallergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        catallergy.setForeground(new java.awt.Color(255, 255, 255));
        catallergy.setText("cat_allergy");
        catallergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catallergyActionPerformed(evt);
            }
        });
        jPanel2.add(catallergy);
        catallergy.setBounds(430, 230, 137, 39);

        dogallergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(dogallergy);
        dogallergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        dogallergy.setForeground(new java.awt.Color(255, 255, 255));
        dogallergy.setText("dog_allergy");
        dogallergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogallergyActionPerformed(evt);
            }
        });
        jPanel2.add(dogallergy);
        dogallergy.setBounds(430, 280, 137, 39);

        birdallergy.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(birdallergy);
        birdallergy.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        birdallergy.setForeground(new java.awt.Color(255, 255, 255));
        birdallergy.setText("birds_allergy");
        birdallergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birdallergyActionPerformed(evt);
            }
        });
        jPanel2.add(birdallergy);
        birdallergy.setBounds(430, 330, 153, 39);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/edit th.png"))); // NOI18N
        jButton1.setText("edit");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(255, 102, 0), null, null));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 470, 230, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("first name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 10, 250, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("last name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 60, 240, 44);

        firstNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNComboActionPerformed(evt);
            }
        });
        jPanel2.add(firstNCombo);
        firstNCombo.setBounds(330, 20, 180, 30);

        lastNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNComboActionPerformed(evt);
            }
        });
        jPanel2.add(lastNCombo);
        lastNCombo.setBounds(330, 70, 180, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 690, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNComboActionPerformed
        
        Object obj = evt.getSource();
        if(obj==firstNCombo)
        {
            
                int clientID = 0;
                try {
                    String sql = "select membership_id from animalsshelter.clients_info where first_name = '" + (firstNCombo.getSelectedItem().toString()) + "'";
                    Statement prep = con.createStatement();
                    ResultSet rst = prep.executeQuery(sql);//resultset contain 1 coloumn the first name
                    
                    while (rst.next())
                    {
                        clientID = rst.getInt(1);
                    }
                    prep.close();
                    rst.close();
                }
                catch (SQLException ex)
                {
                    Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                client_fN.setText(firstNCombo.getSelectedItem().toString());
                fillLastNamecombo();
                
           try {    
                String sqlqry = "select last_name from animalsshelter.clients_info where membership_id = "+clientID;
                PreparedStatement prepred = con.prepareStatement(sqlqry);
                ResultSet resultbred =  prepred.executeQuery();
                
                while (resultbred.next()){
                    lastNCombo.setSelectedItem(resultbred.getString("last_name"));
                    
                }
                resultbred.close();
                resultbred.close();
                
            } 
            catch (SQLException ex)
            {
                Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
            }
            //lastNCombo.removeAllItems();
            //lastNCombo.removeAllItems();
            
        }
        
    }//GEN-LAST:event_firstNComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         java.sql.Date clientDate = null;
              
        try {
            String qury = "select membership_id from animalsshelter.clients_info where first_name = '"+(firstNCombo.getSelectedItem().toString())+"' and last_name = '"+(lastNCombo.getSelectedItem().toString())+"'";
            Statement pss;
            pss = con.createStatement();
            ResultSet rst =  pss.executeQuery(qury);//resultset contain the employee id
            while(rst.next()){
            clientId = rst.getInt(1);}
            pss.close();
            rst.close();
            
            String fname= client_fN.getText();
            String lname = client_ln.getText();
            if (birthDate.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Please Fill The Birth Date Field!");
            }
            try {
                Date birthdd = new SimpleDateFormat("yyyy-MM-dd").parse(birthDate.getText());
                clientDate = convertUtilToSql(birthdd); // to convert from javaDate to sqlDate   
            } catch (ParseException parseException) {
                JOptionPane.showMessageDialog(null, "Please Fill The Date Field In The Form yyyy-mm-dd");
            }
            
            String phonenumb = phone.getText();
            String addresss = address.getText();
            String emaiill = client_email.getText();
            String query = "update animalsshelter.clients_info  set first_name ='"+fname+"' , last_name = '"+lname+"', birth_date = '"+clientDate+"' , phone_number = '"+phonenumb+"' , adress = '"+addresss+"' , email = '"+emaiill+"' , medical_state = "+allrgy+" where membership_id ="+clientId;
        
            Statement stt = con.createStatement();
            stt.execute(query);
            stt.close();
            JOptionPane.showMessageDialog(null, "edited successfully.");
        }
        catch (SQLException ex) {
            Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lastNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNComboActionPerformed
        
        Object obj = evt.getSource();
        if(obj==lastNCombo)
        {
            
        try {
            String sql = "select last_name , birth_date , phone_number , adress , email , medical_state from animalsshelter.clients_info where first_name = '"+(firstNCombo.getSelectedItem().toString())+"' and last_name = '"+(lastNCombo.getSelectedItem().toString())+"'";
            Statement prep = con.createStatement();
            ResultSet rst =  prep.executeQuery(sql);//resultset contain 6 coloumns found by the first name
            
            while(rst.next())
            {
                meddicalstate = rst.getInt(6);
                client_ln.setText(rst.getString(1));
                birthDate.setText(rst.getString(2));
                phone.setText(rst.getString(3));
                address.setText(rst.getString(4));
                client_email.setText(rst.getString(5));
            }
            prep.close();
            rst.close();
        } catch (SQLException ex) {
            Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
            switch (meddicalstate) {
                case 1:
                    noallergy.setSelected(true);
                    break;
                case 2:
                    dogallergy.setSelected(true);
                    break;
                case 3:
                    catallergy.setSelected(true);
                    break;
                case 4:
                    birdallergy.setSelected(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error! No Meddical Statement Found.");
                    break;
            }
        
        }
    }//GEN-LAST:event_lastNComboActionPerformed

    private void noallergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noallergyActionPerformed
        allrgy = 1;
    }//GEN-LAST:event_noallergyActionPerformed

    private void catallergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catallergyActionPerformed
        allrgy = 3;
    }//GEN-LAST:event_catallergyActionPerformed

    private void dogallergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogallergyActionPerformed
        allrgy = 2;
    }//GEN-LAST:event_dogallergyActionPerformed

    private void birdallergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birdallergyActionPerformed
        allrgy = 4;
    }//GEN-LAST:event_birdallergyActionPerformed

    
    private void fillfirstNamecombo()
     {
        try {
            String sqll = "SELECT first_name FROM animalsshelter.clients_info";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                firstNCombo.addItem(rst.getString("first_name"));
                
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
     
     private void fillLastNamecombo()
     {
        // lastNCombo.removeAllItems();
        try {
            String sqll = "SELECT last_name FROM animalsshelter.clients_info where first_name = '"+(firstNCombo.getSelectedItem().toString())+"'";
            PreparedStatement prep = con.prepareStatement(sqll);
            ResultSet rst =  prep.executeQuery();
            
            while (rst.next()){
                lastNCombo.addItem(rst.getString("last_name"));
            }
            prep.close();
            rst.close();
            
            }
        catch (SQLException ex) {
            Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
     
     void createConnection()
    {
         String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(edit_client1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_client1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_client1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JRadioButton birdallergy;
    private javax.swing.JTextField birthDate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton catallergy;
    private javax.swing.JTextField client_email;
    private javax.swing.JTextField client_fN;
    private javax.swing.JTextField client_ln;
    private javax.swing.JRadioButton dogallergy;
    private javax.swing.JComboBox<String> firstNCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lastNCombo;
    private javax.swing.JRadioButton noallergy;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
