/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalshleter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author BT
 */
public class login2 extends javax.swing.JFrame {

    public static int ID;
    Connection con;
    /**
     * Creates new form login2
     */
    public login2() {
        initComponents();
        createConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        email_employee = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        password_employee = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("animal shelter");
        setMinimumSize(new java.awt.Dimension(524, 501));
        setPreferredSize(new java.awt.Dimension(524, 501));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 10, 119, 56);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 90);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 420));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/App-login-manager-icon.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 20, 150, 140);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/username.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 0, 50, 32);

        email_employee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 2));
        jPanel3.add(email_employee);
        email_employee.setBounds(60, 0, 210, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(120, 170, 270, 30);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        jPanel4.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/password.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, -4, 32, 40);

        password_employee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel4.add(password_employee);
        password_employee.setBounds(60, 0, 210, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(120, 230, 270, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/lolo.png"))); // NOI18N
        jButton1.setText("login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(0, 51, 51), null, null));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(170, 310, 160, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 530, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String name = null;
        
        try {
            String sql ="select employee_name from animalsshelter.employees_info where employee_email=? and employee_password =?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, email_employee.getText());
            stmt.setString(2, password_employee.getText());
            ResultSet rst =  stmt.executeQuery();
            
            while (rst.next())
            {
                name = rst.getString("employee_name");
            }
            if(name != null)
            {
                JOptionPane.showMessageDialog(null, "Welcom " + name + " ^^");

               try {
                    int id = 0;
                    String str = "select employee_id from animalsshelter.employees_info where employee_email = '"+email_employee.getText()+"'";
                    Statement ss = con.createStatement();
                    ResultSet rrr = ss.executeQuery(str);
                    while(rrr.next())
                    {
                    id = rrr.getInt("employee_id");
                    }
                    ss.close();
                    rrr.close();
                    ID = id;
                } 
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "couldnt");
                    Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
                }
               new main_menue1().setVisible(true);
               this.setVisible(false);

            }
            else
                JOptionPane.showMessageDialog(null, "Email or Password is incorrect!");
            
            stmt.close();
            rst.close();
           
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Email or Password is incorrect!");
            Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
     void createConnection()
    {
         String url = "jdbc:mysql://127.0.0.1:3306/animalsshelter";
        try {
            con = DriverManager.getConnection(url, "root", "4434544345");
        } catch (SQLException ex) {
            Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_employee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField password_employee;
    // End of variables declaration//GEN-END:variables

   
}
